#!/bin/bash
# Snapshot the full bootstrap state of the current machine to a checked-in
# file. The snapshot is reproducibility insurance: if a future install breaks,
# this file documents the last-known-good combination of formula versions,
# mise pins, submodule SHAs, and plugin commits.
#
# Not byte-reproducible (we'd need Nix for that), but human-auditable and
# diff-friendly across commits. Run after every install you're happy with.
#
# Usage:
#   ./install.sh --snapshot          # writes bootstrap-state.snapshot
#   ./install.sh --snapshot --check  # exit 1 if snapshot is stale
# shellcheck source=lib/_common.sh
. "$DOTFILES_DIR/lib/_common.sh"

SNAPSHOT_FILE="$DOTFILES_DIR/bootstrap-state.snapshot"

snapshot_generate() {
  echo "# bootstrap-state.snapshot — last-known-good system state"
  echo "# Generated by: ./install.sh --snapshot"
  echo "# Format: stable, human-diffable. Compare across commits to see drift."
  echo ""

  echo "## mise tools (from mise.toml)"
  if [ -f "$DOTFILES_DIR/mise.toml" ]; then
    grep -E "^[[:space:]]*[\"a-z]" "$DOTFILES_DIR/mise.toml" \
      | grep -E '=' | sed 's/^/  /'
  fi
  echo ""

  echo "## Brewfile formulae + casks"
  if command -v brew >/dev/null 2>&1 && [ -f "$DOTFILES_DIR/Brewfile" ]; then
    # Capture what's actually installed for everything declared in Brewfile.
    # This catches the case where Brewfile says `brew "tmux"` (latest) but
    # the local install is pinned to a specific version.
    brew bundle list --file="$DOTFILES_DIR/Brewfile" 2>/dev/null \
      | while read -r pkg; do
        local v
        v="$(brew list --versions "$pkg" 2>/dev/null | awk '{$1=""; print substr($0,2)}')"
        printf "  %-30s %s\n" "$pkg" "${v:-(not installed)}"
      done
  fi
  echo ""

  echo "## git submodules"
  if [ -d "$DOTFILES_DIR/.git" ]; then
    git -C "$DOTFILES_DIR" submodule status 2>/dev/null \
      | sed 's/^/  /'
  fi
  echo ""

  echo "## nvim plugins (lazy-lock.json sha)"
  if [ -f "$DOTFILES_DIR/config/nvim/lazy-lock.json" ]; then
    local hash
    hash="$(shasum -a 256 "$DOTFILES_DIR/config/nvim/lazy-lock.json" | awk '{print $1}')"
    echo "  lazy-lock.json sha256: $hash"
  fi
  echo ""

  echo "## tmux plugins (HEAD commits)"
  if [ -d "$HOME/.tmux/plugins" ]; then
    for plugin_dir in "$HOME/.tmux/plugins"/*; do
      [ -d "$plugin_dir/.git" ] || continue
      local plugin sha
      plugin="$(basename "$plugin_dir")"
      sha="$(git -C "$plugin_dir" rev-parse --short HEAD 2>/dev/null || echo "?")"
      printf "  %-30s %s\n" "$plugin" "$sha"
    done
  fi
  echo ""

  echo "## marketing-skills sibling repo (HEAD)"
  local skills_dir="$HOME/Projects/src/github.com/itsmeduncan/ai-marketing-skills"
  if [ -d "$skills_dir/.git" ]; then
    local sha
    sha="$(git -C "$skills_dir" rev-parse --short HEAD 2>/dev/null || echo "?")"
    echo "  ai-marketing-skills HEAD: $sha"
  fi
  echo ""

  echo "## macOS version"
  if [ "$(uname)" = "Darwin" ]; then
    echo "  $(sw_vers -productName) $(sw_vers -productVersion) ($(sw_vers -buildVersion))"
  fi
}

snapshot_run() {
  local mode="${SNAPSHOT_MODE:-write}"

  case "$mode" in
    check)
      if ! diff -u "$SNAPSHOT_FILE" <(snapshot_generate) >/dev/null 2>&1; then
        warn "bootstrap-state.snapshot is stale vs current system"
        warn "Run: ./install.sh --snapshot"
        if [ "${CHECK_MODE:-0}" = "1" ]; then
          return 0
        fi
        return 1
      fi
      ok "bootstrap-state.snapshot in sync with current system"
      ;;
    write)
      if [ "${DRY_RUN:-0}" = "1" ]; then
        would "write $SNAPSHOT_FILE"
        return 0
      fi
      snapshot_generate >"$SNAPSHOT_FILE"
      ok "wrote $SNAPSHOT_FILE"
      ;;
  esac
}
